version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-southeast-1"
    ECR_ACCOUNT_ID: "030370283995"
    ECR_REPO: "cent-test"
  shell: bash

phases:
  pre_build:
    commands:
      - set -euo pipefail
      - ECR_REGISTRY="${ECR_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - REPOSITORY_URI="${ECR_REGISTRY}/${ECR_REPO}"
      - aws ecr get-login-password --region "${AWS_DEFAULT_REGION}" | docker login --username AWS --password-stdin "${ECR_REGISTRY}"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "${REPOSITORY_URI}:latest" .
      - docker tag "${REPOSITORY_URI}:latest" "${REPOSITORY_URI}:${IMAGE_TAG}"

  post_build:
    commands:
      - echo "Pushing Docker image"
      - docker push "${REPOSITORY_URI}:latest"
      - docker push "${REPOSITORY_URI}:${IMAGE_TAG}"
      - printf '{"ImageURI":"%s"}' "${REPOSITORY_URI}:${IMAGE_TAG}" > imageDetail.json
      - echo "Build completed on $(date)"

artifacts:
  files:
    - 'imageDetail.json'
    - 'appspec.yml'
    - 'taskdef.json'

  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json